CREATE TABLE `categorias` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` varchar(100) NOT NULL,
  `PATH_IMAGEN` varchar(100) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID_UNIQUE` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `clientes` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `EMAIL` varchar(100) NOT NULL,
  `APELLIDO` varchar(45) NOT NULL,
  `NOMBRE` varchar(45) NOT NULL,
  `DIRECCION` varchar(100) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID_UNIQUE` (`ID`),
  UNIQUE KEY `EMAIL_UNIQUE` (`EMAIL`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `estado_pedidos` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` varchar(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `id_UNIQUE` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `productos` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` varchar(100) NOT NULL,
  `DESCRIPCION_AMPLIA` varchar(200) NOT NULL,
  `FECHA_VTO` date NOT NULL,
  `STOCK_DISPONIBLE` int NOT NULL,
  `NOMBRE_IMAGEN` varchar(45) NOT NULL,
  `PRECIO` decimal(10,2) NOT NULL,
  `IDSUBCATEGORIA` int NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID_UNIQUE` (`ID`),
  KEY `IDSUBCATEGORIA_idx` (`IDSUBCATEGORIA`),
  CONSTRAINT `IDSUBCATEGORIA` FOREIGN KEY (`IDSUBCATEGORIA`) REFERENCES `subcategoria` (`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `subcategoria` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` varchar(100) NOT NULL,
  `PATH_IMAGEN` varchar(100) NOT NULL,
  `IDCATEGORIA` int NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID_UNIQUE` (`ID`),
  KEY `IDCATEGORIA_idx` (`IDCATEGORIA`),
  CONSTRAINT `IDCATEGORIA` FOREIGN KEY (`IDCATEGORIA`) REFERENCES `categorias` (`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `pedidos` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `FECHA_COMPRA` date NOT NULL,
  `IDCLIENTE` int NOT NULL,
  `IDPRODUCTO` int NOT NULL,
  `CANTIDAD` int NOT NULL,
  `PRECIO` double NOT NULL,
  `IMPORTE` double NOT NULL,
  `IDESTADO` int NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID_UNIQUE` (`ID`),
  KEY `IDCLIENTE_idx` (`IDCLIENTE`),
  KEY `IDPRODUCTO_idx` (`IDPRODUCTO`),
  KEY `IDESTADO_idx` (`IDESTADO`),
  CONSTRAINT `IDCLIENTE` FOREIGN KEY (`IDCLIENTE`) REFERENCES `clientes` (`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `IDESTADO` FOREIGN KEY (`IDESTADO`) REFERENCES `estado_pedidos` (`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `IDPRODUCTO` FOREIGN KEY (`IDPRODUCTO`) REFERENCES `productos` (`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
